import type { Project } from "./types"

export const mockProject: Project = {
  id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  numeroProcesso: "138/2025",
  uasg: "153034 - Universidade Federal do Rio de Janeiro",
  responsavel: "Ana Carolina Mendes Silva",
  dataPesquisa: "2025-09-15",
  items: [
    {
      numeroItem: 1,
      descricao: "Papel A4, 75g/m2, branco, resma com 500 folhas",
      quantidadeEstimada: 2000,
      metrics: { media: 24.5, mediana: 23.9, desvioPadrao: 4.2, cv: 17.1 },
      cotacoes: [
        {
          id: "q1a",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Kalunga Com. e Ind. Grafica Ltda",
          fornecedorCNPJ: "43.283.811/0001-50",
          dataCompra: "2025-03-10",
          valorOriginal: 22.5,
          valorAtualizado: 22.5,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q1b",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Papelaria Central Eireli",
          fornecedorCNPJ: "12.345.678/0001-90",
          dataCompra: "2025-05-22",
          valorOriginal: 23.9,
          valorAtualizado: 23.9,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q1c",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "Office Max Brasil S.A.",
          fornecedorCNPJ: "98.765.432/0001-10",
          dataCompra: "2025-06-18",
          valorOriginal: 25.3,
          valorAtualizado: 25.3,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q1d",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Distribuidora ABC Ltda",
          fornecedorCNPJ: "55.123.456/0001-78",
          dataCompra: "2025-01-08",
          valorOriginal: 21.8,
          valorAtualizado: 21.8,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q1e",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "Staples Brasil Com. Ltda",
          fornecedorCNPJ: "33.222.111/0001-44",
          dataCompra: "2024-07-30",
          valorOriginal: 45.0,
          valorAtualizado: 45.0,
          status: "EXCLUIDO_OUTLIER_ALTO",
          motivoExclusao:
            "Valor discrepante removido para homogeneizacao (CV > 25%)",
        },
        {
          id: "q1f",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Papelaria Escolar ME",
          fornecedorCNPJ: "11.222.333/0001-55",
          dataCompra: "2024-02-12",
          valorOriginal: 19.5,
          valorAtualizado: 19.5,
          status: "EXCLUIDO_TEMPO",
          motivoExclusao: "Data superior a 1 ano da pesquisa",
        },
        {
          id: "q1g",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "MegaPapel Distribuicao Ltda",
          fornecedorCNPJ: "77.888.999/0001-22",
          dataCompra: "2025-08-05",
          valorOriginal: 26.2,
          valorAtualizado: 26.2,
          status: "VALIDO",
          motivoExclusao: "",
        },
      ],
    },
    {
      numeroItem: 2,
      descricao:
        "Caneta esferografica, ponta media 1.0mm, tinta azul, corpo transparente",
      quantidadeEstimada: 5000,
      metrics: { media: 1.85, mediana: 1.79, desvioPadrao: 0.38, cv: 20.5 },
      cotacoes: [
        {
          id: "q2a",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "BIC do Brasil S.A.",
          fornecedorCNPJ: "61.099.008/0001-41",
          dataCompra: "2025-04-15",
          valorOriginal: 1.45,
          valorAtualizado: 1.45,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q2b",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "Faber-Castell Ltda",
          fornecedorCNPJ: "59.596.908/0001-52",
          dataCompra: "2025-06-20",
          valorOriginal: 1.79,
          valorAtualizado: 1.79,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q2c",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Papelaria Brasil Ltda",
          fornecedorCNPJ: "44.555.666/0001-77",
          dataCompra: "2025-07-03",
          valorOriginal: 2.1,
          valorAtualizado: 2.1,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q2d",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Atacadao Escritorio ME",
          fornecedorCNPJ: "22.333.444/0001-88",
          dataCompra: "2025-02-28",
          valorOriginal: 2.05,
          valorAtualizado: 2.05,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q2e",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "CIS Companhia Ind. H. Schneider",
          fornecedorCNPJ: "60.397.164/0001-43",
          dataCompra: "2025-05-12",
          valorOriginal: 1.89,
          valorAtualizado: 1.89,
          status: "VALIDO",
          motivoExclusao: "",
        },
      ],
    },
    {
      numeroItem: 3,
      descricao:
        "Toner para impressora laser HP CF226A, preto, rendimento 3.100 paginas",
      quantidadeEstimada: 200,
      metrics: { media: 189.6, mediana: 185.0, desvioPadrao: 52.3, cv: 27.6 },
      cotacoes: [
        {
          id: "q3a",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "HP Brasil Industria e Comercio",
          fornecedorCNPJ: "02.413.345/0001-68",
          dataCompra: "2025-03-25",
          valorOriginal: 289.9,
          valorAtualizado: 289.9,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q3b",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "TonnerBrasil Comercio Ltda",
          fornecedorCNPJ: "88.777.666/0001-33",
          dataCompra: "2025-05-10",
          valorOriginal: 155.0,
          valorAtualizado: 155.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q3c",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "InfoStore Distribuicao S.A.",
          fornecedorCNPJ: "66.555.444/0001-22",
          dataCompra: "2025-07-15",
          valorOriginal: 185.0,
          valorAtualizado: 185.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q3d",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "MicroTech Informatica ME",
          fornecedorCNPJ: "11.999.888/0001-66",
          dataCompra: "2025-04-01",
          valorOriginal: 210.5,
          valorAtualizado: 210.5,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q3e",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "Print Center Com. Ltda",
          fornecedorCNPJ: "99.888.777/0001-11",
          dataCompra: "2025-08-20",
          valorOriginal: 168.0,
          valorAtualizado: 168.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q3f",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Kalunga Com. e Ind. Grafica Ltda",
          fornecedorCNPJ: "43.283.811/0001-50",
          dataCompra: "2025-06-30",
          valorOriginal: 195.0,
          valorAtualizado: 195.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
      ],
    },
    {
      numeroItem: 4,
      descricao:
        "Monitor LED 24 polegadas, Full HD 1920x1080, painel IPS, entrada HDMI/VGA",
      quantidadeEstimada: 50,
      metrics: { media: 892.0, mediana: 879.0, desvioPadrao: 98.5, cv: 11.0 },
      cotacoes: [
        {
          id: "q4a",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Dell Computadores do Brasil Ltda",
          fornecedorCNPJ: "72.381.189/0001-10",
          dataCompra: "2025-02-15",
          valorOriginal: 879.0,
          valorAtualizado: 879.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q4b",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "Samsung Eletronica da Amazonia",
          fornecedorCNPJ: "00.280.273/0001-37",
          dataCompra: "2025-04-22",
          valorOriginal: 920.0,
          valorAtualizado: 920.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q4c",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "LG Electronics do Brasil Ltda",
          fornecedorCNPJ: "01.166.372/0001-55",
          dataCompra: "2025-05-30",
          valorOriginal: 845.0,
          valorAtualizado: 845.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q4d",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Positivo Tecnologia S.A.",
          fornecedorCNPJ: "81.243.735/0001-48",
          dataCompra: "2025-07-10",
          valorOriginal: 995.0,
          valorAtualizado: 995.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
      ],
    },
    {
      numeroItem: 5,
      descricao:
        "Cadeira giratoria executiva, assento e encosto em tecido mesh, apoio de bracos regulavel",
      quantidadeEstimada: 30,
      metrics: {
        media: 1250.0,
        mediana: 1195.0,
        desvioPadrao: 315.0,
        cv: 25.2,
      },
      cotacoes: [
        {
          id: "q5a",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Flexform Industria Metalurgica S.A.",
          fornecedorCNPJ: "47.229.950/0001-80",
          dataCompra: "2025-01-20",
          valorOriginal: 1195.0,
          valorAtualizado: 1195.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q5b",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "Cavaletti S.A. Cadeiras Profissionais",
          fornecedorCNPJ: "89.898.650/0001-17",
          dataCompra: "2025-03-18",
          valorOriginal: 1450.0,
          valorAtualizado: 1450.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q5c",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Escritolux Comercio Ltda",
          fornecedorCNPJ: "22.111.000/0001-99",
          dataCompra: "2025-06-05",
          valorOriginal: 980.0,
          valorAtualizado: 980.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q5d",
          datasetFonte: "PARAM_II_CONTRATACOES_SIMILARES",
          fornecedorNome: "Frisokar Industria e Comercio",
          fornecedorCNPJ: "55.777.888/0001-44",
          dataCompra: "2025-07-22",
          valorOriginal: 1650.0,
          valorAtualizado: 1650.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
        {
          id: "q5e",
          datasetFonte: "PARAM_I_SISTEMAS_OFICIAIS",
          fornecedorNome: "Marelli Moveis para Escritorio Ltda",
          fornecedorCNPJ: "33.444.555/0001-66",
          dataCompra: "2025-08-15",
          valorOriginal: 1120.0,
          valorAtualizado: 1120.0,
          status: "VALIDO",
          motivoExclusao: "",
        },
      ],
    },
  ],
}
